# 無効にするルール
disabled_rules:
- type_name # クラス名は長くして情報を詰めておく必要もある為、無効

# ルール一覧を表示
#- colon
#- control_statement
#- file_length
#- force_cast
#- function_body_length
#- leading_whitespace
#- line_length
#- nesting
#- operator_whitespace
#- return_arrow_whitespace
#- todo
#- trailing_newline
#- type_body_length
#- variable_name

# 一行の文字列制限を100文字から300文字に変更
line_length: 300

included: # Lint対象のファイルのあるパスを記述
- ../../EnlargedThumbSlider/Classes

