use_frameworks!

target 'EnlargedThumbSlider_Example' do
  pod 'EnlargedThumbSlider', :path => '../'

  target 'EnlargedThumbSlider_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 2.1.0'
    pod 'Nimble', '~> 8.0.2'
  end
end
