use_frameworks!

target 'EnlargedThumbSlider_Example' do
  pod 'EnlargedThumbSlider', :path => '../'

  target 'EnlargedThumbSlider_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
